// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEbhkUBznjjQaf73xwlzdJCydn5lvpRP0',
    appId: '1:409884115393:android:18c4ee2572efe3b7502f40',
    messagingSenderId: '409884115393',
    projectId: 'study-app-dabfe',
    databaseURL: 'https://study-app-dabfe-default-rtdb.firebaseio.com',
    storageBucket: 'study-app-dabfe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlj6ANI5f9Ghxq6eTox_zbmZ24usK6AZM',
    appId: '1:409884115393:ios:274142c1b2195721502f40',
    messagingSenderId: '409884115393',
    projectId: 'study-app-dabfe',
    databaseURL: 'https://study-app-dabfe-default-rtdb.firebaseio.com',
    storageBucket: 'study-app-dabfe.appspot.com',
    androidClientId: '409884115393-2n013tqp17j1eg7ok4fldph363moqqsf.apps.googleusercontent.com',
    iosClientId: '409884115393-qcgvcdign8q6n7s656lj3eokss3crn34.apps.googleusercontent.com',
    iosBundleId: 'com.example.vidsCom',
  );
}
